### ISSUE TITLE
Running into an issue for parsing a really long string.

### ISSUE THREAD

**Issue by kurikyoma** [stencillogic/num-bigfloat#3]
In the following situation:

```
        println!("input: {}", input);
        let val = match BigFloat::parse(input) {
            Some(s) => s,
            None => return None,
        };
        println!("val: {}", val.to_string());
```

The following are being treated as though they are identical:

input: 100000000000000000000000000000000000000000000.00000000000000000000000000000000000000001
val: 1.000000000000000000000000000000000000000e+39
input: 100000000000000000000000000000000000000000000.00000000000000000000000000000000000000002
val: 1.000000000000000000000000000000000000000e+39

When I compare them using .cmp() it returns 0.

**Comment by kurikyoma** [comment]
Actually here it is more succinctly:

```
fn main() {
    let input1 = "100000000000000000000000000000000000000000000.00000000000000000000000000000000000000002";
    let input2 = "100000000000000000000000000000000000000000000.00000000000000000000000000000000000000001";

    let bigfloat1 = BigFloat::parse(input1).unwrap();
    let bigfloat2 = BigFloat::parse(input2).unwrap();

    println!("The comparison value of these is: {}", bigfloat1.cmp(&bigfloat2).unwrap())
}
```

output:
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target\debug\decimal.exe`
The comparison value of these is: 0
```

**Comment by stencillogic** [comment]
`BigFloat` in `num-bigfloat` can only provide precision of 40 decimal digits. For greater precision you can take a look at [astro-float](https://github.com/stencillogic/astro-float).

**Comment by kurikyoma** [comment]
Ah okay, thanks for pointing me there.
