### ISSUE TITLE
problem with minus zero not equal to zero

### ISSUE THREAD

**Issue by ludrol** [stencillogic/num-bigfloat#6]
`assert!(BigFloat::from(-1).frac() == BigFloat::from(0))` 
is not equal to true

-0 is not equal to 0 

Is this a bug?

some code for debugging
```rust
    let a = BigFloat::from(-1).frac();  
    let b = BigFloat::from(0);  
    assert!(a==b);
```

**Comment by ludrol** [comment]
here is offending comparison

https://github.com/stencillogic/num-bigfloat/blob/f311c0747f4effb5fed0c28bd04509de53cf3163/src/ops/other.rs#L86



here is construction of -0 

https://github.com/stencillogic/num-bigfloat/blob/f311c0747f4effb5fed0c28bd04509de53cf3163/src/ext.rs#L1603

**Comment by stencillogic** [comment]
Yes, seems like that. Thanks for raising the issue.

**Comment by stencillogic** [comment]
> here is offending comparison
> 
> https://github.com/stencillogic/num-bigfloat/blob/f311c0747f4effb5fed0c28bd04509de53cf3163/src/ops/other.rs#L86
> 
> here is construction of -0
> 
> https://github.com/stencillogic/num-bigfloat/blob/f311c0747f4effb5fed0c28bd04509de53cf3163/src/ext.rs#L1603

-0 must be equal 0 of course. The library does not respect sign of zero and may change it here and there, but both -0 and 0 can still appear. So, this

https://github.com/stencillogic/num-bigfloat/blob/f311c0747f4effb5fed0c28bd04509de53cf3163/src/ops/other.rs#L86

should go after

https://github.com/stencillogic/num-bigfloat/blob/f311c0747f4effb5fed0c28bd04509de53cf3163/src/ops/other.rs#L98

I guess this should fix the problem.
